REQUEST_TYPE_CHOICES = (
    ('00-00', ''),
    ('01-00', 'Actualización - Historia académica por doble titulación'),
    ('01-01', 'Actualización - Historia académica por traslado'),
    ('01-02', 'Actualización - Líneas de actas para estudiantes de doble titulación'),
    ('01-03', 'Actualización - Equivalencia de asignaturas por doble titulación'),
    ('01-04', 'Actualización - Equivalencia de asignaturas por traslado'),
    ('01-05', 'Actualización - Historia académica por traslado Inter-Facultad'),
    ('01-06', 'Actualización - Régimen de convalidaciones y equivalencias por traslado'),
    ('02-00', 'Modificación - Calificación'),
    ('02-01', 'Modificación - Calificación en actividad académica'),
    ('02-02', 'Modificación - Estudio de homologación'),
    ('02-03', 'Modificación - Director'),
    ('02-04', 'Modificación - Tutor'),
    ('02-05', 'Modificación - Jurado'),
    ('02-06', 'Modificación - Evaluador'),
    ('02-07', 'Modificación - Co-director'),
    ('02-08', 'Modificación - Título Trabajo Final Maestría'),
    ('02-09', 'Modificación - Título Tesis de Maestría'),
    ('02-10', 'Modificación - Título Tesis de Doctorado'),
    ('02-11', 'Modificación - Fecha para pasantía'),
    ('02-12', 'Modificación - Formalización de admisión para estudiantes con admisión anticipada al posgrado'),
    ('02-13', 'Modificación - Créditos a otorgar aprobados'),
    ('02-14', 'Modificación - Resolución'),
    ('02-15', 'Modificación - Asignaturas a cursar en intercambio académico nacional'),
    ('02-16', 'Modificación - Asignaturas a cursar en intercambio académico internacional'),
    ('02-17', 'Modificación - Asignaturas a homologar en intercambio académico'),
    ('02-18', 'Modificación - Convalidación de asignatura'),
    ('02-19', 'Modificación - Homologación de asignatura'),
    ('02-20', 'Modificación - Homologación de asignaturas por intercambio académico internacional'),
    ('02-21', 'Modificación - Homologación de asignaturas por intercambio académico nacional'),
    ('02-22', 'Modificación - Homologación suficiencia lengua extranjera'),
    ('02-23', 'Modificación - Equivalencia de asignatura'),
    ('02-24', 'Modificación - Equivalencia de asignatura por traslado'),
    ('02-25', 'Modificación - Transferencia de líneas de acta'),
    ('02-26', 'Modificación - Otro'),
    ('03-00', 'Cancelación - Asignatura'),
    ('03-01', 'Cancelación - Asignatura posterior a mitad de periodo académico'),
    ('03-02', 'Cancelación - Actividad académica - Seminario'),
    ('03-03', 'Cancelación - Actividad académica - Examen calificación'),
    ('03-04', 'Cancelación - Actividad académica - Pasantía'),
    ('03-05', 'Cancelación - Actividad académica - Trabajo final'),
    ('03-06', 'Cancelación - Actividad académica - Tesis'),
    ('03-07', 'Cancelación - Actividad académica - Propuesta de trabajo final'),
    ('03-08', 'Cancelación - Actividad académica - Proyecto de tesis'),
    ('03-09', 'Cancelación - Periodo académico'),
    ('03-10', 'Cancelación - No oportuna de asignatura'),
    ('03-11', 'Cancelación - No oportuna de actividad académica'),
    ('03-12', 'Cancelación - Movilidad académica internacional'),
    ('03-13', 'Cancelación - Movilidad académica nacional'),
    ('03-14', 'Cancelación - Doble titulación'),
    ('03-15', 'Cancelación - Prórroga de intercambio académico'),
    ('03-16', 'Cancelación - Grafo MAP'),
    ('03-17', 'Cancelación - Movilidad Inter-Sede'),
    ('04-00', 'Inscripción - Asignaturas'),
    ('04-01', 'Inscripción - Actividad académica - Seminario'),
    ('04-02', 'Inscripción - Actividad académica - Examen calificación'),
    ('04-03', 'Inscripción - Actividad académica - Pasantía'),
    ('04-04', 'Inscripción - Actividad académica - Trabajo final'),
    ('04-05', 'Inscripción - Actividad académica - Tesis'),
    ('04-06', 'Inscripción - Actividad académica - Propuesta de trabajo final'),
    ('04-07', 'Inscripción - Actividad académica - Proyecto de tesis'),
    ('05-00', 'Eliminación - Líneas de acta'),
    ('06-00', 'Restablecimiento - Asignaturas'),
    ('06-01', 'Restablecimiento - Actividad académica'),
    ('06-02', 'Restablecimiento - Líneas de acta'),
    ('07-00', 'Reingreso - Único reingreso'),
    ('07-01', 'Reingreso - Segundo reingreso'),
    ('08-00', 'Equivalencias - Asignaturas'),
    ('08-01', 'Equivalencias - Asignaturas cursadas y aprobadas en MAP'),
    ('09-00', 'Estudio equivalencias - Asignaturas para doble titulación'),
    ('09-01', 'Estudio equivalencias - Asignaturas por cambio plan de estudios'),
    ('10-00', 'Estudio homologación - Asignaturas en intercambio académico nacional'),
    ('10-01', 'Estudio homologación - Asignaturas en intercambio académico internacional'),
    ('11-00', 'Pérdida de calidad de estudiante - Por retiro definitivo del programa curricular'),
    ('11-01', 'Pérdida de calidad de estudiante - Por no renovar matrícula'),
    ('11-02', 'Pérdida de calidad de estudiante - Por promedio bajo'),
    ('11-03', 'Pérdida de calidad de estudiante - Máximo tiempo permanencia'),
    ('12-00', 'Intercambio académico - Convenio Universidad de los Andes'),
    ('12-01', 'Intercambio académico - Convenio Universidad Javeriana'),
    ('12-02', 'Intercambio académico - Nacional'),
    ('12-03', 'Intercambio académico - Internacional'),
    ('13-00', 'Otorgamiento cupo - Extraordinario de créditos para cumplir con su plan de estudios'),
    ('13-01', 'Otorgamiento cupo - Extraordinario de créditos por doble titulación'),
    ('14-00', 'Doble titulación - Doble titulación'),
    ('15-00', 'Distinción - Meritoria Tesis Maestría'),
    ('15-01', 'Distinción - Meritoria Tesis Doctorado'),
    ('15-02', 'Distinción - Laureada Tesis Maestría'),
    ('15-03', 'Distinción - Laureada Tesis Doctorado'),
    ('15-04', 'Distinción - Grado de honor pregrado'),
    ('15-05', 'Distinción - Matrícula de honor pregrado'),
    ('15-06', 'Distinción - Exención de pago pregrado'),
    ('15-07', 'Distinción - Mejores trabajos de grado de pregrado'),
    ('16-00', 'Mención - Meritoria Trabajo Final'),
    ('17-00', 'Homologación - Suficiencia lengua extranjera'),
    ('17-01', 'Homologación - Asignaturas'),
    ('17-02', 'Homologación - Asignaturas por convenio'),
    ('17-03', 'Homologación - Asignaturas en intercambio academico convenio SIGUEME'),
    ('17-04', 'Homologación - Asignaturas cursadas en intercambio académico nacional'),
    ('17-05', 'Homologación - Asignaturas cursadas en intercambio académico internacional'),
    ('17-06', 'Homologación - Pasantía realizada en intercambio académico internacional'),
    ('18-00', 'Recurso - Recurso de reposición'),
    ('18-01', 'Recurso - Recurso de reposición en subsidio de apelación'),
    ('19-00', 'Registro - Calificación'),
    ('20-00', 'Excepción - Excepción'),
    ('21-00', 'Carga inferior a la mínima - Carga inferior a la mínima'),
    ('22-00', 'Autorización/aval - Aval para cursar pasantía'),
    ('22-01', 'Autorización/aval - Autorización para cursar asignaturas prerrequisito y requisito en el mismo periodo'),
    ('22-02', 'Autorización/aval - Realizar pasantía en la misma institución que realizó práctica profesional'),
    ('23-00', 'Transferencias de líneas de acta - Transferencia de líneas de acta'),
    ('24-00', 'Cambio - Grupo de asignatura'),
    ('24-01', 'Cambio - Grupo Trabajo de Grado'),
    ('24-02', 'Cambio - Tipología de asignatura'),
    ('24-03', 'Cambio - Nodo'),
    ('25-00', 'Aprobación - Proyecto de Tesis'),
    ('25-01', 'Aprobación - Requisito de grado – Publicación'),
    ('25-02', 'Aprobación - Propuesta Trabajo Final'),
    ('25-03', 'Aprobación - Extemporánea de Trabajo de Grado'),
    ('26-00', 'Traslado - Intersede'),
    ('26-01', 'Traslado - Interfacultad'),
    ('26-02', 'Traslado - Intrafacultad'),
    ('27-00', 'Desbloqueo - Historia académica'),
    ('27-01', 'Desbloqueo - Desbloqueo'),
    ('28-00', 'Desistimiento - Movilidad académica'),
    ('28-01', 'Desistimiento - De cupo de admisión'),
    ('28-02', 'Desistimiento - Reingreso'),
    ('28-03', 'Desistimiento - Traslado intersede'),
    ('28-04', 'Desistimiento - Traslado interfacultad'),
    ('28-05', 'Desistimiento - Traslado intrafacultad'),
    ('28-06', 'Desistimiento - Cupo en doble titulación'),
    ('28-07', 'Desistimiento - Cancelación asignatura'),
    ('28-08', 'Desistimiento - Inscripción no oportuna asignatura'),
    ('28-09', 'Desistimiento - Otro'),
    ('29-00', 'Reconocimiento - Por resultados obtenidos en la prueba SABER PRO'),
    ('30-00', 'Designación - Tutor'),
    ('30-01', 'Designación - Evaluador'),
    ('30-02', 'Designación - Tercer evaluador'),
    ('30-03', 'Designación - Director'),
    ('30-04', 'Designación - Codirector'),
    ('30-05', 'Designación - Jurados'),
    ('31-00', 'Tránsito - Tránsito entre programas'),
    ('32-00', 'Retiro - Retiro del programa curricular'),
    ('33-00', 'Reserva de cupo - Reserva de cupo'),
    ('33-01', 'Reserva de cupo - Reserva de cupo adicional'),
    ('34-00', 'Prórroga - Intercambio académico nacional'),
    ('34-01', 'Prórroga - Intercambio académico internacional'),
    ('35-00', 'Devolución - Valor de matrícula por exención de pago a estudiantes por logros obtenidos en actividades culturales'),
    ('35-01', 'Devolución - Por cancelación de periodo académico'),
    ('35-02', 'Devolución - Créditos por cancelación de asignaturas'),
    ('36-00', 'Movilidad - Movilidad entre sedes'),
    ('36-01', 'Movilidad - Movilidad nacional'),
    ('36-02', 'Movilidad - Movilidad internacional'),
    ('37-00', 'Aplazamiento - Uso del derecho de matrícula'),
    ('38-00', 'Exención - Pago de matrícula'),
)